example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://database:5432/eagle_eye_local"
spring.datasource.username: "postgres"
spring.datasource.password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
test: 123


#spring.db-product-service.driverClassName: "com.mysql.cj.jdbc.Driver"
#spring.db-product-service.jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.db-product-service.username: root
#spring.db-product-service.password: 1234
#spring.db-product-service.testOnBorrow: true
#spring.db-product-service.testWhileIdle: true
#spring.db-product-service.timeBetweenEvictionRunsMillis: 60000
#spring.db-product-service.minEvictableIdleTimeMillis: 30000
#spring.db-product-service.validationQuery: SELECT 1
#spring.db-product-service.max-active: 15
#spring.db-product-service.max-idle: 10