server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    service-url:
          defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
