server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri:
          search-paths: http://github.com/carnellj/config-repo/
          username: username
          password: password
#       基于本地配置文件的配置
#        native:
#          search-locations: file:///C:\SpringCloud\SpringCloud\config-server\src\main\resources\config\licensingservice